name: Build, Test and Check plugin

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'CONTRIBUTING.md'
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  Build-Test-Check:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        jvm_version: [21]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Move project to C drive on Windows
        if: matrix.os == 'windows'
        run: |
          mkdir -p /c/gradle-scala-extras
          cp -r ./* .* /c/gradle-scala-extras
          ls -alh /c/gradle-scala-extras
      - name: Build, test, check and dry deployment
        uses: DanySK/build-check-deploy-gradle-action@3.3.0
        with:
          build-command: |
            if [[ "$RUNNER_OS" == "Windows" ]]; then
              cd /c/gradle-scala-extras
            fi
            ./gradlew classes testClasses --parallel
          check-command: |
            if [[ "$RUNNER_OS" == "Windows" ]]; then
                cd /c/gradle-scala-extras
            fi
            ./gradlew check --parallel
          deploy-command: >-
            ./gradlew
            uploadKotlinOSSRHToMavenCentralNexus
            uploadPluginMavenToMavenCentralNexus
            uploadPluginMarkerMavenToMavenCentralNexus
            close
            drop
            --parallel
          should-run-codecov: false
          should-deploy: >-
            ${{
              runner.os == 'Linux'
              && !github.event.repository.fork
              && github.event_name != 'pull_request'
            }}
          maven-central-username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          maven-central-password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          signing-key: ${{ secrets.SIGNING_KEY }}
          signing-password: ${{ secrets.SIGNING_PASSWORD }}
