name: Build, Test and Check plugin

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'CONTRIBUTING.md'
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  Build-Test-Check:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        jvm_version: [21] # [11, 17, 21]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Move project to C drive if on Windows
        if: matrix.os == 'windows'
        run: |
          mkdir -p /c/gradle-scala-qa
          mv ./* /c/gradle-scala-qa
          ls -alh /c/gradle-scala-qa
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.jvm_version }}
      - name: Build
        env:
          GH_USERNAME: ${{ env.GH_USERNAME }}
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            cd /c/gradle-scala-qa
          fi
          ./gradlew classes testClasses
      - name: Test
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
              cd /c/gradle-scala-qa
          fi
          ./gradlew test
      - name: Check
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
              cd /c/gradle-scala-qa
          fi
          ./gradlew check
